MATHPIX_API_ID = "e0036818_u_nus_edu_5c5a56_2375f0"
MATHPIX_API_KEY = "7f07985f0c117c53eef8"
LOGIN_ENDPOINT = "/api/v1/auth/login"

loginUrl = "http://jackett-development-v1.ap-southeast-1.elasticbeanstalk.com/api/v1/auth/login"
ADD_QUESTION_URL = "http://jackett-development-v1.ap-southeast-1.elasticbeanstalk.com/api/v2/questions/addQuestion"
IMAGE_DETECTION_URL = "http://13.212.127.75:5000/api/v1/image/getAnnotationPrediction?layout_type=layout_2"
UPLOAD_IMAGE_URL = "http://jackett-development-v1.ap-southeast-1.elasticbeanstalk.com/api/resource/upload-base64-image"
BBOX_MONGO_URL = "mongodb+srv://mongo_jackett:fCmWGwxTJYiq3znL@cluster2.ilgpxd2.mongodb.net/test?retryWrites=true&w=majority"
JACKETT_WEBSERVICE_URL = "http://jackett-development-v1.ap-southeast-1.elasticbeanstalk.com"